In [4]:
# 1. Given a random array, change the sign of elements whose values between 3 and 8
import numpy as np

# 1. Генерируем массив
arr = np.random.randint(0, 16, size=15)
print("1. Исходный массив:      ", arr)

# 2. Создаем маску для чисел между 3 и 8
mask = (arr > 3) & (arr < 8)

# 3. Меняем знак у элементов, которые попадают под маску
arr[mask] = -arr[mask]

print("2. После изменения знака:", arr)

1. Исходный массив:       [11 12  5 11  8 14  2 12 15 11  3 11  4  5  6]
2. После изменения знака: [11 12 -5 11  8 14  2 12 15 11  3 11 -4 -5 -6]


In [5]:
# 2. Replace the maximum element of a random array with 0

# 1. Создаем массив
arr2 = np.random.randint(0, 20, size=10)
print("1. Исходный массив:     ", arr2)

# 2. Находим максимум
max_value = arr2.max()
print("   Максимальный элемент:", max_value)

# 3. Заменяем на 0 (способ через маску)
arr2[arr2 == max_value] = 0

print("2. После замены:        ", arr2)

1. Исходный массив:      [ 7 13  8 14 13  1 14  6 10  1]
   Максимальный элемент: 14
2. После замены:         [ 7 13  8  0 13  1  0  6 10  1]


In [6]:
# 3. Construct the direct product of arrays (all combinations with each element). A two-dimensional array is provided as input.
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5])

# Способ 1: Используем np.meshgrid
grid1, grid2 = np.meshgrid(arr1, arr2)
direct_product = np.vstack([grid1.ravel(), grid2.ravel()]).T

print("Прямое произведение:")
print(direct_product)

Прямое произведение:
[[1 4]
 [2 4]
 [3 4]
 [1 5]
 [2 5]
 [3 5]]


In [7]:
# 4. Given two arrays, A (8x3) and B (2x2), find rows in A that contain elements from each row in B, regardless of the order of the elements in B.
# Создаем тестовые массивы
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [2, 1, 7],  # содержит 1 и 2 (из первой строки B)
    [8, 9, 10],
    [5, 4, 11], # содержит 4 и 5 (из второй строки B)
    [1, 3, 5],
    [6, 4, 5],  # содержит 4 и 5
    [2, 8, 9]
])

B = np.array([
    [1, 2],  # ищем строки, содержащие 1 и 2
    [4, 5]   # ищем строки, содержащие 4 и 5
])

# Решение: проверяем каждую строку A
result_rows = []

for row_b in B:  # для каждой строки в B
    for i, row_a in enumerate(A):  # для каждой строки в A
        # Проверяем, все ли элементы из row_b есть в row_a
        if np.all(np.isin(row_b, row_a)):
            result_rows.append(i)

# Убираем дубликаты индексов
result_rows = list(set(result_rows))
result = A[result_rows]

print("Строки из A, содержащие элементы из B:")
print(result)
print("Индексы строк:", result_rows)

Строки из A, содержащие элементы из B:
[[ 1  2  3]
 [ 4  5  6]
 [ 2  1  7]
 [ 5  4 11]
 [ 6  4  5]]
Индексы строк: [0, 1, 2, 4, 6]


In [8]:
# 5. Given a 10x3 matrix, find rows of unequal values (for example, the row [2,2,3] remains, the row [3,3,3] is deleted)
# Создаем тестовую матрицу 10x3
matrix = np.array([
    [1, 2, 3],  # остается (разные)
    [2, 2, 2],  # удаляется (все равны)
    [4, 5, 4],  # остается
    [3, 3, 3],  # удаляется
    [1, 1, 2],  # остается
    [7, 7, 7],  # удаляется
    [8, 9, 10], # остается
    [5, 5, 5],  # удаляется
    [1, 2, 1],  # остается
    [6, 6, 6]   # удаляется
])

# Способ 1: Проверяем, все ли элементы в строке равны первому
mask = ~np.all(matrix == matrix[:, [0]], axis=1)
result = matrix[mask]

print("Строки с неравными значениями:")
print(result)

# Способ 2: Через min и max (более понятный)
mask2 = (matrix.min(axis=1) != matrix.max(axis=1))
result2 = matrix[mask2]

print("\nТот же результат другим способом:")
print(result2)

Строки с неравными значениями:
[[ 1  2  3]
 [ 4  5  4]
 [ 1  1  2]
 [ 8  9 10]
 [ 1  2  1]]

Тот же результат другим способом:
[[ 1  2  3]
 [ 4  5  4]
 [ 1  1  2]
 [ 8  9 10]
 [ 1  2  1]]


In [10]:
# 6. Given a two-dimensional array, remove the rows that are repeated.
import numpy as np

# Тестовый массив с повторяющимися строками
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],  # дубликат строки 0
    [7, 8, 9],
    [4, 5, 6]   # дубликат строки 1
])

# Решение: используем np.unique с axis=0
unique_arr = np.unique(arr, axis=0)

print("Оригинал:")
print(arr)
print("\nБез дубликатов:")
print(unique_arr)

Оригинал:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]

Без дубликатов:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#For each of the following problems (1-5) you need to provide 2 implementations – one without using numpy (Consider that where the input or output should be a numpy array, there will simply be lists), and the second one is fully vectorized using numpy (without using Python loops/map/list comprehension).

#Note 1. It can be assumed that all specified objects are non-empty (for example, in task 1 there are non-zero elements on the diagonal of the matrix).

#Note 2. For most tasks, the solution takes no more than 1-2 lines.

#Task 6.1: Calculate the product of nonzero elements on the diagonal of a rectangular matrix.
#For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) answer is 3.

import numpy as np
from math import prod

X = np.array([[1, 0, 1],
              [2, 0, 2],
              [3, 0, 3],
              [4, 4, 4]])

#  Решение БЕЗ NumPy
def diagonal_product_no_numpy(matrix):
    # Получаем диагональ (минимальное из rows/cols)
    rows = len(matrix)
    cols = len(matrix[0]) if rows > 0 else 0
    diag_length = min(rows, cols)

    # Извлекаем диагональ
    diagonal = [matrix[i][i] for i in range(diag_length)]

    # Фильтруем нули и считаем произведение
    nonzero_diag = [x for x in diagonal if x != 0]
    return prod(nonzero_diag) if nonzero_diag else 1

# ✅ Решение С NumPy
def diagonal_product_numpy(matrix):
    diag = np.diag(matrix)  # извлекаем диагональ
    return np.prod(diag[diag != 0])  # произведение ненулевых

print("Без NumPy:", diagonal_product_no_numpy(X.tolist()))
print("С NumPy:", diagonal_product_numpy(X))

Без NumPy: 3
С NumPy: 3


In [12]:
#Task 6.2: Two vectors x and y are given. Check if they define the same multiset.
#For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) answer is True.

import numpy as np

x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

#  Решение БЕЗ NumPy
def same_multiset_no_numpy(x, y):
    return sorted(x) == sorted(y)

# ✅ Решение С NumPy
def same_multiset_numpy(x, y):
    return np.array_equal(np.sort(x), np.sort(y))

print("Без NumPy:", same_multiset_no_numpy(x.tolist(), y.tolist()))
print("С NumPy:", same_multiset_numpy(x, y))

Без NumPy: True
С NumPy: True


In [13]:
#Task 6.3: Find the maximum element in the vector x among the elements preceded by zero. For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) answer is 5.

import numpy as np

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
# Индексы:    0  1  2  3  4  5  6  7  8
# После 0 идут:    3  0  5  (элементы на позициях 3, 5, 7)

#  Решение БЕЗ NumPy
def max_after_zero_no_numpy(x):
    result = []
    for i in range(len(x) - 1):
        if x[i] == 0:
            result.append(x[i + 1])
    return max(result) if result else None

# ✅ Решение С NumPy
def max_after_zero_numpy(x):
    # Находим индексы, где элемент = 0
    zero_indices = np.where(x[:-1] == 0)[0]
    # Берем элементы ПОСЛЕ каждого нуля
    elements_after_zero = x[zero_indices + 1]
    return np.max(elements_after_zero)

print("Без NumPy:", max_after_zero_no_numpy(x.tolist()))
print("С NumPy:", max_after_zero_numpy(x))

Без NumPy: 5
С NumPy: 5


In [14]:
#Task 6.4: Implement run-length encoding. For some vector x, it is necessary to return a tuple of two vectors of the same length. The first one contains numbers and the second one contains how many times they need to be repeated.
#For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

import numpy as np

x = np.array([2, 2, 2, 3, 3, 3, 5])
# Ответ: (values=[2, 3, 5], counts=[3, 3, 1])

# ❌ Решение БЕЗ NumPy
def rle_no_numpy(x):
    if not x:
        return [], []

    values = [x[0]]
    counts = [1]

    for i in range(1, len(x)):
        if x[i] == x[i-1]:
            counts[-1] += 1
        else:
            values.append(x[i])
            counts.append(1)

    return values, counts

# ✅ Решение С NumPy
def rle_numpy(x):
    # Находим позиции, где элемент меняется
    diff_indices = np.where(x[:-1] != x[1:])[0] + 1
    # Добавляем начало и конец
    indices = np.concatenate(([0], diff_indices, [len(x)]))
    # Извлекаем уникальные значения
    values = x[indices[:-1]]
    # Считаем длины серий
    counts = np.diff(indices)
    return values, counts

values, counts = rle_numpy(x)
print("Values:", values)   # [2 3 5]
print("Counts:", counts)   # [3 3 1]


Values: [2 3 5]
Counts: [3 3 1]


In [16]:
# Task 6.5: Two samples of objects are given - X and Y. Calculate the matrix of Euclidean distances between objects. Compare with function scipy.spatial.distance.cdist by operating speed.

import numpy as np
from scipy.spatial.distance import cdist
import time

# Тестовые данные
X = np.array([[1, 2], [3, 4], [5, 6]])
Y = np.array([[0, 1], [2, 3]])

# ❌ Решение БЕЗ NumPy (наивное)
def euclidean_distances_no_numpy(X, Y):
    result = []
    for x in X:
        row = []
        for y in Y:
            # Евклидово расстояние: sqrt(sum((xi - yi)^2))
            dist = sum((xi - yi) ** 2 for xi, yi in zip(x, y)) ** 0.5
            row.append(dist)
        result.append(row)
    return result

# ✅ Решение С NumPy (векторизованное)
def euclidean_distances_numpy(X, Y):
    # Используем broadcasting
    # X: (n, d) -> (n, 1, d)
    # Y: (m, d) -> (1, m, d)
    # Разность: (n, m, d)
    diff = X[:, np.newaxis, :] - Y[np.newaxis, :, :]
    # Квадрат разности и сумма по последнему измерению
    distances = np.sqrt(np.sum(diff ** 2, axis=2))
    return distances

# ✅ Решение с scipy (для сравнения скорости)
def euclidean_distances_scipy(X, Y):
    return cdist(X, Y, metric='euclidean')

# Проверяем результаты
print("NumPy result:\n", euclidean_distances_numpy(X, Y))
print("SciPy result:\n", euclidean_distances_scipy(X, Y))

# Сравнение скорости
n_runs = 1000

# Замер NumPy
start = time.time()
for _ in range(n_runs):
    euclidean_distances_numpy(X, Y)
numpy_time = time.time() - start

# Замер SciPy
start = time.time()
for _ in range(n_runs):
    cdist(X, Y, metric='euclidean')
scipy_time = time.time() - start

print(f"\nNumPy время: {numpy_time:.4f} сек")
print(f"SciPy время: {scipy_time:.4f} сек")
print(f"SciPy быстрее в {numpy_time/scipy_time:.2f} раз")

NumPy result:
 [[1.41421356 1.41421356]
 [4.24264069 1.41421356]
 [7.07106781 4.24264069]]
SciPy result:
 [[1.41421356 1.41421356]
 [4.24264069 1.41421356]
 [7.07106781 4.24264069]]

NumPy время: 0.0255 сек
SciPy время: 0.0116 сек
SciPy быстрее в 2.21 раз


In [17]:
#Task 6: CrunchieMunchies
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

In [18]:
#6.2 One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

# Task 6.2
average_calories = np.mean(calorie_stats) - 60
print("Разница со средней калорийностью конкурентов:", average_calories)

Разница со средней калорийностью конкурентов: 46.883116883116884


In [19]:
#6.3 Does the average calorie count accurately reflect the distribution of the data set? Let's sort the data and see.
# Task 6.3
calorie_stats_sorted = np.sort(calorie_stats)
print("Отсортированные данные:")
print(calorie_stats_sorted)

Отсортированные данные:
[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


In [20]:
#6.4
#It looks like most values are above the mean. Let's see if the median is the most accurate measure of the data set.

# Task 6.4
median_calories = np.median(calorie_stats)
print("Медиана:", median_calories)
print("Среднее значение:", np.mean(calorie_stats))

Медиана: 110.0
Среднее значение: 106.88311688311688


In [21]:
#6.5
#While the median shows that at least half of our values are over 100 calories, it would be more impressive to show that a significant portion of the competitors have higher calorie counts than CrunchieMunchies.

# Task 6.5
# Проверяем разные процентили
for percentile in range(0, 100, 5):
    value = np.percentile(calorie_stats, percentile)
    print(f"{percentile}-й процентиль: {value}")
    if value > 60:
        nth_percentile = percentile
        break

print(f"\nМинимальный процентиль, превышающий 60 калорий: {nth_percentile}")

0-й процентиль: 50.0
5-й процентиль: 70.0

Минимальный процентиль, превышающий 60 калорий: 5


In [22]:
#6.6
#While the percentile shows us that most competitors have much higher calorie counts, it's an awkward concept to use in marketing materials.

# Task 6.6
more_calories = np.mean(calorie_stats > 60) * 100
print(f"Процент хлопьев с калорийностью выше 60: {more_calories}%")

Процент хлопьев с калорийностью выше 60: 96.1038961038961%


In [23]:
#6.7
#This is a really high percentage. This will be very useful as we promote CrunchieMunchies. But one question is: how big are the differences in the dataset? Can we generalize that most cereals contain around 100 calories or is the range even wider?

# Task 6.7
calorie_std = np.std(calorie_stats)
print("Стандартное отклонение:", calorie_std)

# Дополнительно: можно показать диапазон
mean = np.mean(calorie_stats)
print(f"\nСреднее: {mean}")
print(f"Диапаон [среднее ± std]: [{mean - calorie_std}, {mean + calorie_std}]")

Стандартное отклонение: 19.35718533390827

Среднее: 106.88311688311688
Диапаон [среднее ± std]: [87.52593154920862, 126.24030221702515]


In [24]:
#6.8
#Please write a short paragraph outlining your findings and how you believe this data can be used to Mycrunch's advantage in marketing CrunchieMunchies.

# Task 6.8
print("""
МАРКЕТИНГОВЫЕ ВЫВОДЫ:

1. CrunchieMunchies (60 калорий) значительно ниже средней калорийности конкурентов
   (среднее: {:.1f} калорий, разница: {:.1f} калорий).

2. Медиана ({:.1f} калорий) показывает, что более половины всех хлопьев имеют
   калорийность выше 100 калорий.

3. {:.0f}% конкурентов имеют калорийность выше 60 калорий - это означает, что
   CrunchieMunchies калорийнее только {:.0f}% рынка.

4. Стандартное отклонение ({:.1f}) показывает большой разброс в калорийности
   между брендами, что подчеркивает разнообразие выбора на рынке.

5. Наш продукт - один из самых низкокалорийных на рынке, что делает его
   идеальным выбором для здорового питания!
""".format(
    np.mean(calorie_stats),
    average_calories,
    median_calories,
    more_calories,
    100 - more_calories,
    calorie_std
))


МАРКЕТИНГОВЫЕ ВЫВОДЫ:

1. CrunchieMunchies (60 калорий) значительно ниже средней калорийности конкурентов 
   (среднее: 106.9 калорий, разница: 46.9 калорий).

2. Медиана (110.0 калорий) показывает, что более половины всех хлопьев имеют 
   калорийность выше 100 калорий.

3. 96% конкурентов имеют калорийность выше 60 калорий - это означает, что 
   CrunchieMunchies калорийнее только 4% рынка.

4. Стандартное отклонение (19.4) показывает большой разброс в калорийности 
   между брендами, что подчеркивает разнообразие выбора на рынке.

5. Наш продукт - один из самых низкокалорийных на рынке, что делает его 
   идеальным выбором для здорового питания!

